export const activeSale=r=>!['cancelled','rejected','expired'].includes(r.status);
export const sum=(rows,key)=>rows.reduce((a,r)=>a+Number(r[key]||0),0);
export const financeSummary=(reservations,expenses,month)=>{const selected=reservations.filter(r=>activeSale(r)&&String(r.checkIn).slice(0,7)===month),costs=expenses.filter(e=>String(e.date).slice(0,7)===month);const sales=sum(selected,'total'),paid=sum(selected,'paid'),fees=sum(selected,'channelCommission'),spent=sum(costs,'amount'),depositPending=selected.reduce((a,r)=>a+Math.max(0,Math.min(Number(r.total)-Number(r.paid),Number(r.depositRequired||0)-Number(r.paid))),0);return{selected,costs,sales,paid,fees,spent,depositPending,balance:sales-paid,estimated:sales-fees-spent}};
export const cabinRows=(cabins,selected,costs,payments=[],month='')=>cabins.map(c=>{const rows=selected.filter(r=>r.cabinId===c.id),expenses=costs.filter(e=>e.cabinId===c.id),cash=payments.filter(p=>p.cabinId===c.id&&(!month||String(p.paidAt||p.createdAt).slice(0,7)===month)),total=sum(rows,'total'),paid=sum(rows,'paid'),fees=sum(rows,'channelCommission'),spent=sum(expenses,'amount'),cashIn=sum(cash.filter(p=>p.kind!=='refund'),'amount'),refunds=sum(cash.filter(p=>p.kind==='refund'),'amount'),netCash=cashIn-refunds;return{id:c.id,name:c.name,count:rows.length,total,paid,fees,spent,cashIn,refunds,netCash,estimated:total-fees-spent,margin:total?((total-fees-spent)/total)*100:0}});

const nightsBetween=(a,b)=>Math.max(0,Math.round((Date.parse(String(b).slice(0,10)+'T00:00:00Z')-Date.parse(String(a).slice(0,10)+'T00:00:00Z'))/86400000));
export const performanceRows=(cabins,reservations,month)=>{const start=month+'-01',d=new Date(start+'T00:00:00Z'),end=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,1)).toISOString().slice(0,10),days=nightsBetween(start,end);return cabins.map(c=>{const rows=reservations.filter(r=>activeSale(r)&&r.cabinId===c.id&&String(r.checkIn).slice(0,10)<end&&String(r.checkOut).slice(0,10)>start);let sold=0,revenue=0;for(const r of rows){const a=String(r.checkIn).slice(0,10)>start?String(r.checkIn).slice(0,10):start,b=String(r.checkOut).slice(0,10)<end?String(r.checkOut).slice(0,10):end,n=nightsBetween(a,b),all=nightsBetween(r.checkIn,r.checkOut);sold+=n;if(all)revenue+=Number(r.total||0)*(n/all)}const adr=sold?revenue/sold:0,occupancy=days?sold/days*100:0,revpar=days?revenue/days:0;return{id:c.id,name:c.name,days,sold,revenue:Math.round(revenue),adr:Math.round(adr),occupancy,revpar:Math.round(revpar)}})};

export const monthlyTrend=(cabins,reservations,expenses,payments,month,count=6)=>{const anchor=new Date(month+'-01T00:00:00Z');return Array.from({length:count},(_,i)=>{const d=new Date(Date.UTC(anchor.getUTCFullYear(),anchor.getUTCMonth()-(count-1-i),1)),m=d.toISOString().slice(0,7),f=financeSummary(reservations,expenses,m),perf=performanceRows(cabins,reservations,m),sold=sum(perf,'sold'),available=perf.reduce((a,x)=>a+x.days,0),revenue=sum(perf,'revenue'),cash=payments.filter(p=>String(p.paidAt||p.createdAt).slice(0,7)===m),cashIn=sum(cash.filter(p=>p.kind!=='refund'),'amount'),refunds=sum(cash.filter(p=>p.kind==='refund'),'amount');return{month:m,sales:f.sales,estimated:f.estimated,cashIn,refunds,netCash:cashIn-refunds,sold,occupancy:available?sold/available*100:0,adr:sold?Math.round(revenue/sold):0,revpar:available?Math.round(revenue/available):0}})};
