import React,{useState}from'react';
import{channelName}from'./calendarDates.js';
import{financeSummary,cabinRows,sum}from'./financeMath.js';
const money=n=>'$'+Number(n||0).toLocaleString('es-CL');
export default function RealFinance({reservations,cabins,expenses,payments=[],action,call,busy}){
 const [month,setMonth]=useState(new Date().toLocaleDateString('en-CA',{timeZone:'America/Santiago'}).slice(0,7)),[draft,setDraft]=useState({date:new Date().toLocaleDateString('en-CA',{timeZone:'America/Santiago'}),cabinId:'',category:'Limpieza',description:'',amount:''}),[commission,setCommission]=useState({});
 const {selected,costs,sales,paid,fees,spent,depositPending,balance,estimated}=financeSummary(reservations,expenses,month);const cash=payments.filter(p=>String(p.paidAt||p.createdAt).slice(0,7)===month),cashIn=sum(cash.filter(p=>p.kind!=='refund'),'amount'),cashOut=sum(cash.filter(p=>p.kind==='refund'),'amount'),netCash=cashIn-cashOut;
 const grouped=(key)=>Object.entries(Object.groupBy(selected,r=>r[key]||'Sin asignar')).map(([name,rows])=>({name,rows,total:sum(rows,'total'),paid:sum(rows,'paid'),fees:sum(rows,'channelCommission')}));
 return <><article className="card pagecard"><h2>Informe financiero por fecha de entrada</h2><p>Ventas agrupadas por mes de llegada, no por fecha del pago. Gastos según fecha registrada. Comisiones manuales; no se transfieren fondos.</p><label>Mes <input type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><section className="kpis"><article className="kpi"><p>Ingresos recibidos en el mes</p><h2>{money(cashIn)}</h2></article><article className="kpi"><p>Devoluciones del mes</p><h2>{money(cashOut)}</h2></article><article className="kpi"><p>Flujo neto recibido</p><h2>{money(netCash)}</h2></article><article className="kpi"><p>Ventas</p><h2>{money(sales)}</h2></article><article className="kpi"><p>Cobrado neto</p><h2>{money(paid)}</h2></article><article className="kpi"><p>Saldos por cobrar</p><h2>{money(balance)}</h2></article><article className="kpi"><p>Anticipos pendientes</p><h2>{money(depositPending)}</h2></article><article className="kpi"><p>Gastos</p><h2>{money(spent)}</h2></article><article className="kpi"><p>Comisiones anotadas</p><h2>{money(fees)}</h2></article><article className="kpi"><p>Resultado estimado</p><h2>{money(estimated)}</h2></article></section><p>Resultado estimado = ventas − gastos registrados − comisiones registradas. No equivale a utilidad contable ni considera impuestos u otros costos no ingresados.</p></article>
 <article className="card pagecard"><h2>Movimientos de caja del mes</h2><p>Estos montos se agrupan por la fecha real registrada del cobro o devolución, independientemente de la fecha de llegada.</p>{!cash.length&&<p>Sin movimientos en este mes.</p>}{cash.map(p=><p key={p.id}>{String(p.paidAt||p.createdAt).slice(0,10)} · {p.guest} · {p.cabinName} · {p.kind==='refund'?'Devolución':'Ingreso'} · {money(p.amount)} · {p.method||'—'}</p>)}</article><article className="card pagecard"><h2>Por cobrar</h2>{selected.filter(r=>Number(r.total)>Number(r.paid)).map(r=><p key={r.id}>{r.guest} · {r.cabinName} · {money(Number(r.total)-Number(r.paid))}</p>)}</article>
  {['cabinName','source'].map(key=><article className="card pagecard" key={key}><h2>{key==='source'?'Ingresos por canal':'Rentabilidad estimada por alojamiento'}</h2><div className="realGridScroll"><table className="realGrid"><thead><tr><th>{key==='source'?'Canal':'Alojamiento'}</th><th>Reservas</th><th>Ventas</th><th>Cobrado reservas</th>{key==='cabinName'&&<><th>Ingresos caja</th><th>Devoluciones</th><th>Flujo neto</th></>}<th>Comisiones</th><th>Gastos</th><th>Resultado estimado</th>{key==='cabinName'&&<th>Margen</th>}</tr></thead><tbody>{(key==='cabinName'?cabinRows(cabins,selected,costs,payments,month):grouped(key)).map(g=>{const amount=g.spent||0;return <tr key={g.id||g.name}><th>{key==='source'?channelName[g.name]||g.name:g.name}</th><td>{g.count??g.rows.length}</td><td>{money(g.total)}</td><td>{money(g.paid)}</td>{key==='cabinName'&&<><td>{money(g.cashIn)}</td><td>{money(g.refunds)}</td><td>{money(g.netCash)}</td></>}<td>{money(g.fees)}</td><td>{key==='source'?'—':money(amount)}</td><td>{key==='source'?'—':money(g.estimated)}</td>{key==='cabinName'&&<td>{g.total?g.margin.toFixed(1)+'%':'—'}</td>}</tr>})}</tbody></table></div>{key==='cabinName'&&<p>Gastos generales sin cabaña asignada: {money(sum(costs.filter(e=>!e.cabinId),'amount'))}. No se distribuyen automáticamente entre alojamientos.</p>}</article>)}
 <article className="card pagecard"><h2>Registrar gasto operativo</h2><form className="formgrid" onSubmit={e=>{e.preventDefault();action(async()=>{await call('/operations/expenses',{method:'POST',body:JSON.stringify({...draft,cabinId:draft.cabinId||null,amount:Number(draft.amount)})});setDraft(p=>({...p,description:'',amount:''}))})}}><label>Fecha<input type="date" required value={draft.date} onChange={e=>setDraft(p=>({...p,date:e.target.value}))}/></label><label>Cabaña<select value={draft.cabinId} onChange={e=>setDraft(p=>({...p,cabinId:e.target.value}))}><option value="">Gasto general</option>{cabins.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Categoría<input required value={draft.category} onChange={e=>setDraft(p=>({...p,category:e.target.value}))}/></label><label>Detalle<input maxLength={300} value={draft.description} onChange={e=>setDraft(p=>({...p,description:e.target.value}))}/></label><label>Monto CLP<input type="number" required min="1" value={draft.amount} onChange={e=>setDraft(p=>({...p,amount:e.target.value}))}/></label><button className="new" disabled={busy}>Guardar gasto</button></form>{costs.map(e=><p key={e.id}>{String(e.date).slice(0,10)} · {e.cabinName||'General'} · {e.category} · {money(e.amount)} <button className="soft" disabled={busy} onClick={()=>{if(window.confirm('¿Eliminar este gasto registrado?'))action(()=>call('/operations/expenses/'+e.id,{method:'DELETE'}))}}>Eliminar</button></p>)}</article>
 <article className="card pagecard"><h2>Comisiones de canales externos</h2><p>Registra manualmente el monto de comisión de Booking, Airbnb u otro canal. No realiza pagos ni consulta plataformas.</p>{selected.map(r=><div className="realReservation" key={r.id}><strong>{r.guest} · {r.cabinName} · {channelName[r.source]||r.source}</strong><small>Venta {money(r.total)} · Comisión registrada {money(r.channelCommission)}</small><div><input type="number" aria-label={'Comisión '+r.guest} min="0" max={r.total} placeholder="Comisión CLP" value={commission[r.id]??r.channelCommission??0} onChange={e=>setCommission(p=>({...p,[r.id]:e.target.value}))}/><button className="soft" disabled={busy} onClick={()=>action(()=>call('/operations/reservations/'+r.id+'/commission',{method:'PATCH',body:JSON.stringify({amount:Number(commission[r.id]??r.channelCommission??0)})}))}>Guardar comisión</button></div></div>)}</article></>
}
