import React,{useState}from'react';
import{addDays,activeReservation,coversDay,channelName,dateKey}from'./calendarDates.js';
const TODAY=dateKey(new Date());
export default function RealCalendar({cabins,reservations,blocks,onEdit}){
 const[start,setStart]=useState(TODAY),[days,setDays]=useState(14),[cabinFilter,setCabinFilter]=useState('all');
 const dates=Array.from({length:days},(_,i)=>addDays(start,i));
 const visible=cabins.filter(c=>cabinFilter==='all'||c.id===cabinFilter);
 const occupied=visible.flatMap(c=>dates.map(day=>({c,day}))).filter(({c,day})=>reservations.some(r=>r.cabinId===c.id&&activeReservation(r)&&coversDay(r,day))).length;
 return <article className="card pagecard"><h2>Calendario central · todas las reservas</h2><p>Reservas de cualquier origen registrado manualmente o desde Hospeda. La salida deja libre la noche de ese día.</p>
 <div className="calendarToolbar"><button type="button" className="soft" onClick={()=>setStart(addDays(start,-days))}>← Anterior</button><button type="button" className="soft" onClick={()=>setStart(TODAY)}>Hoy</button><button type="button" className="soft" onClick={()=>setStart(addDays(start,days))}>Siguiente →</button><label>Desde <input aria-label="Inicio del calendario" type="date" value={start} onChange={e=>e.target.value&&setStart(e.target.value)}/></label><label>Vista <select aria-label="Días visibles" value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 días</option><option value={14}>14 días</option><option value={28}>28 días</option></select></label><label>Cabaña <select aria-label="Filtrar cabaña" value={cabinFilter} onChange={e=>setCabinFilter(e.target.value)}><option value="all">Todas las cabañas</option>{cabins.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div>
 <p><strong>{start} → {addDays(start,days)}</strong> · {visible.length} alojamientos · {occupied} noches reservadas de {visible.length*days} disponibles en la vista (sin descontar bloqueos).</p>
 <div className="realGridScroll"><table className="realGrid centralCalendar"><thead><tr><th>Alojamiento</th>{dates.map(day=><th key={day}>{new Date(day+'T12:00:00Z').toLocaleDateString('es-CL',{day:'2-digit',month:'2-digit',timeZone:'UTC'})}</th>)}</tr></thead><tbody>{visible.map(c=><tr key={c.id}><th>{c.name}</th>{dates.map(day=>{const r=reservations.find(r=>r.cabinId===c.id&&activeReservation(r)&&coversDay(r,day));const b=blocks.find(b=>b.cabin_id===c.id&&coversDay(b,day,'check_in','check_out'));const origin=r?channelName[r.source]||r.source:'';const description=r?`${r.guest} · ${origin}${r.sourceReference?' · '+r.sourceReference:''} · ${r.checkIn} a ${r.checkOut}`:b?b.reason:'Disponible';return <td key={day} className={r?'realOccupied':b?'realBlocked':'realFree'} title={description}>{r?<button type="button" className="calendarReservation" aria-label={`${c.name}, ${day}, ${description}`} onClick={()=>onEdit(r)}><strong>{r.guest}</strong><small>{origin}</small></button>:b?<span aria-label={`${c.name}, ${day}, bloqueado: ${b.reason}`} title={b.reason}>×</span>:<span aria-label={`${c.name}, ${day}, disponible`}>·</span>}</td>})}</tr>)}</tbody></table></div>
 <p>Reserva: huésped y canal · × Bloqueo manual · · Disponible. Selecciona una reserva para editarla.</p></article>
}
