import React,{useState}from'react';
export default function RealReservationEditor({reservation,cabins,onSave,onClose,busy,onCancel}){
 const[f,setF]=useState({...reservation,email:reservation.email||'',children:reservation.children||0,notes:reservation.notes||'',checkIn:String(reservation.checkIn).slice(0,10),checkOut:String(reservation.checkOut).slice(0,10)});const set=(k,v)=>setF(p=>({...p,[k]:v}));
 return <div className="modalback" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><div className="modalhead"><h2>Detalle de reserva</h2><button onClick={onClose}>×</button></div><form className="formgrid" onSubmit={e=>{e.preventDefault();onSave({guest:f.guest,phone:f.phone||'',email:f.email||'',cabinId:f.cabinId,checkIn:f.checkIn,checkOut:f.checkOut,people:Number(f.people),children:Number(f.children||0),notes:f.notes||'',total:Number(f.total),status:f.status})}}>
 <label>Huésped<input required value={f.guest} onChange={e=>set('guest',e.target.value)}/></label><label>Teléfono<input value={f.phone||''} onChange={e=>set('phone',e.target.value)}/></label><label>Email<input type="email" value={f.email||''} onChange={e=>set('email',e.target.value)}/></label>
 <label>Alojamiento<select value={f.cabinId} onChange={e=>set('cabinId',e.target.value)}>{cabins.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Adultos<input type="number" min="1" required value={f.people} onChange={e=>set('people',e.target.value)}/></label><label>Niños<input type="number" min="0" value={f.children} onChange={e=>set('children',e.target.value)}/></label>
 <label>Llegada<input type="date" required value={f.checkIn} onChange={e=>set('checkIn',e.target.value)}/></label><label>Salida<input type="date" required value={f.checkOut} onChange={e=>set('checkOut',e.target.value)}/></label><label>Total<input type="number" min="0" required value={f.total} onChange={e=>set('total',e.target.value)}/></label>
 <label>Estado<select value={f.status} onChange={e=>set('status',e.target.value)}><option value="confirmed">Confirmada</option><option value="pending">Pendiente</option><option value="finished">Finalizada</option><option value="cancelled">Cancelada</option><option value="expired">Vencida</option></select></label><label style={{gridColumn:'1/-1'}}>Observaciones<textarea rows="4" maxLength="2000" value={f.notes} onChange={e=>set('notes',e.target.value)} placeholder="Preferencias, solicitudes, información útil para la estadía…"/></label>
 <div className="formactions">{onCancel&&!['cancelled','finished'].includes(f.status)&&<button type="button" className="soft" disabled={busy} onClick={()=>{const reason=window.prompt('Motivo de cancelación');if(reason?.trim())onCancel({reason:reason.trim(),initiatedBy:'guest'})}}>Cancelar reserva</button>}<button type="button" className="soft" onClick={onClose}>Cerrar</button><button disabled={busy} className="new">Guardar cambios</button></div></form></div></div>}
