import {chromium} from 'playwright-core';
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',args:['--no-sandbox']});
const context=await browser.newContext();const page=await context.newPage();page.setDefaultTimeout(6000);const errors=[];page.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:53127';let passed=0,failed=0;
async function test(name,fn){try{await fn();console.log('PASS '+name);passed++}catch(e){console.log('FAIL '+name+' '+e.message);failed++}}
await test('Marketplace renders',async()=>{await page.goto(base+'/marketplace');await page.getByText('Elige dónde quedarte.').waitFor();if(await page.locator('.mpCard').count()!==10)throw Error('Expected 10 cards, got '+await page.locator('.mpCard').count())});
await test('Distinct images',async()=>{const imgs=await page.locator('.mpCard img').evaluateAll(xs=>xs.map(x=>x.src));if(new Set(imgs).size!==10)throw Error('Duplicate image URLs: '+new Set(imgs).size)});
await test('Images load',async()=>{await page.locator('.mpCard img').evaluateAll(xs=>Promise.all(xs.map(x=>new Promise(resolve=>{if(x.complete)return resolve();x.addEventListener('load',resolve,{once:true});x.addEventListener('error',resolve,{once:true});setTimeout(resolve,12000)}))));const broken=await page.locator('.mpCard img').evaluateAll(xs=>xs.filter(x=>!x.naturalWidth).map(x=>x.src));if(broken.length)throw Error('Broken images: '+broken.join(', '))});
await test('Filter capacity',async()=>{await page.locator('.mpSearch select').selectOption('6');if(await page.locator('.mpCard').count()!==2)throw Error('Expected 2 for 6 guests, got '+await page.locator('.mpCard').count());await page.locator('.mpSearch select').selectOption('2')});
await test('Filter destination',async()=>{await page.locator('.mpSearch input').first().fill('Villarrica');if(await page.locator('.mpCard').count()!==3)throw Error('Expected 3 Villarrica properties, got '+await page.locator('.mpCard').count());await page.locator('.mpSearch input').first().fill('')});
await test('Featured listing controls',async()=>{await page.goto(base+'/');await page.locator('nav button').filter({hasText:'Marketplace'}).click();await page.getByText('Hospeda Marketplace').waitFor();await page.locator('.mpAdminRows input').first().check();await page.goto(base+'/marketplace');if(await page.locator('.mpSponsored').count()!==1)throw Error('Sponsored missing');});
await test('Reservation flow and commission',async()=>{await page.locator('.mpCardText button').first().click();await page.locator('.reserveCard input').first().fill('QA Test');await page.locator('.reserveCard input').last().fill('+56912345678');await page.getByRole('button',{name:'Solicitar reserva'}).click();await page.getByText('Solicitud registrada').waitFor();const r=await page.evaluate(()=>JSON.parse(localStorage.getItem('hospeda-reservations')).at(-1));if(r.source!=='hospeda_marketplace'||r.commissionAmount!==Math.round(r.total*.1)||r.status!=='Pendiente')throw Error(JSON.stringify(r));});
await test('Booking removes availability',async()=>{if(await page.locator('.mpCard').count()!==9)throw Error('Expected 9 after booking')});
await test('Admin sees booking',async()=>{await page.goto(base+'/');await page.locator('nav button').filter({hasText:'Reservas'}).click();await page.getByText('QA Test').waitFor()});
await test('No JS errors',async()=>{if(errors.length)throw Error(errors.join(' | '))});
console.log(`RESULT ${passed} passed ${failed} failed`);await browser.close();process.exitCode=failed?1:0;
