import{Router}from'express';import{z}from'zod';import{pool,q}from'../config/db.js';import{auth}from'../middleware/auth.js';import{validate}from'../lib/validate.js';
const r=Router();r.use(auth);
r.get('/arrivals',async(req,res,next)=>{try{const date=z.iso.date().safeParse(req.query.date||new Date().toLocaleDateString('en-CA',{timeZone:'America/Santiago'}));if(!date.success)return res.status(400).json({error:'Fecha inválida'});res.json((await q(`select r.id,c.name "cabinName",g.full_name guest,r.check_in "checkIn",r.check_out "checkOut",r.checked_in_at "checkedInAt",r.checked_out_at "checkedOutAt",r.status from reservations r join cabins c on c.id=r.cabin_id and c.organization_id=r.organization_id join guests g on g.id=r.guest_id and g.organization_id=r.organization_id where r.organization_id=$1 and r.status in ('confirmed','pending','finished') and (r.check_in=$2 or r.check_out=$2) order by r.check_in,c.name`,[req.user.org,date.data])).rows)}catch(e){next(e)}});
r.patch('/reservations/:id/visit',validate(z.object({action:z.enum(['check_in','check_out'])})),async(req,res,next)=>{const c=await pool.connect();try{await c.query('begin');const row=(await c.query('select * from reservations where id=$1 and organization_id=$2 for update',[req.params.id,req.user.org])).rows[0];if(!row){await c.query('rollback');return res.status(404).json({error:'Reserva no encontrada'})}const inAction=req.body.action==='check_in';if(row.status!=='confirmed'||inAction&&(row.checked_in_at||row.checked_out_at)||!inAction&&(!row.checked_in_at||row.checked_out_at)){await c.query('rollback');return res.status(409).json({error:'Transición de estadía inválida'})}const today=new Date().toLocaleDateString('en-CA',{timeZone:'America/Santiago'});if(inAction&&today<String(row.check_in).slice(0,10)||!inAction&&today<String(row.check_in).slice(0,10)){await c.query('rollback');return res.status(409).json({error:'No se puede registrar el movimiento antes de la llegada'})}const result=(await c.query(inAction?'update reservations set checked_in_at=now() where id=$1 and organization_id=$2 returning id,checked_in_at "checkedInAt",checked_out_at "checkedOutAt",status':'update reservations set checked_out_at=now(),status=\'finished\' where id=$1 and organization_id=$2 returning id,checked_in_at "checkedInAt",checked_out_at "checkedOutAt",status',[row.id,req.user.org])).rows[0];if(!inAction){await c.query("insert into operations_tasks(organization_id,cabin_id,reservation_id,type,status,due_at) values($1,$2,$3,'cleaning','pending',now()) on conflict do nothing",[req.user.org,row.cabin_id,row.id])}await c.query('commit');res.json(result)}catch(e){await c.query('rollback');next(e)}finally{c.release()}});
r.patch('/reservations/:id/commission',validate(z.object({amount:z.coerce.number().int().min(0).max(100000000)})),async(req,res,next)=>{try{const result=await q('update reservations set channel_commission=$3 where id=$1 and organization_id=$2 and gross_amount>=$3 returning id,channel_commission "channelCommission"',[req.params.id,req.user.org,req.body.amount]);if(!result.rowCount)return res.status(404).json({error:'Reserva no encontrada o comisión superior al total'});res.json(result.rows[0])}catch(e){next(e)}});
r.get('/expenses',async(req,res,next)=>{try{res.json((await q('select e.id,e.cabin_id "cabinId",c.name "cabinName",e.expense_date "date",e.category,e.description,e.amount from operating_expenses e left join cabins c on c.id=e.cabin_id and c.organization_id=e.organization_id where e.organization_id=$1 order by e.expense_date desc,e.created_at desc',[req.user.org])).rows)}catch(e){next(e)}});
r.post('/expenses',validate(z.object({cabinId:z.string().uuid().nullable().optional(),date:z.iso.date(),category:z.string().trim().min(2).max(80),description:z.string().trim().max(300).default(''),amount:z.coerce.number().int().positive().max(100000000)})),async(req,res,next)=>{try{const x=req.body;if(x.cabinId){const cabin=await q('select id from cabins where id=$1 and organization_id=$2',[x.cabinId,req.user.org]);if(!cabin.rowCount)return res.status(404).json({error:'Alojamiento no encontrado'})}res.status(201).json((await q('insert into operating_expenses(organization_id,cabin_id,expense_date,category,description,amount) values($1,$2,$3,$4,$5,$6) returning *',[req.user.org,x.cabinId||null,x.date,x.category,x.description,x.amount])).rows[0])}catch(e){next(e)}});
r.delete('/expenses/:id',async(req,res,next)=>{try{const result=await q('delete from operating_expenses where id=$1 and organization_id=$2 returning id',[req.params.id,req.user.org]);if(!result.rowCount)return res.status(404).json({error:'Gasto no encontrado'});res.json({ok:true})}catch(e){next(e)}});
export default r;
