import 'dotenv/config';import express from'express';import cors from'cors';import pg from'pg';import bcrypt from'bcryptjs';import jwt from'jsonwebtoken';import multer from'multer';import path from'path';import fs from'fs';import crypto from'crypto';
const app=express(),port=process.env.API_PORT||53128,secret=process.env.JWT_SECRET||'dev-only-change-me',pool=new pg.Pool({connectionString:process.env.DATABASE_URL||'postgresql://localhost/hospeda'});if(process.env.NODE_ENV==='production'&&!process.env.JWT_SECRET)throw Error('JWT_SECRET required in production');app.use(cors({origin:['http://localhost:53127','http://127.0.0.1:53127']}));app.use(express.json());app.use('/uploads',express.static(path.resolve('uploads')));const upload=multer({storage:multer.diskStorage({destination:'uploads/',filename:(r,f,cb)=>cb(null,crypto.randomUUID()+path.extname(f.originalname))}),limits:{fileSize:8*1024*1024,files:12},fileFilter:(r,f,cb)=>cb(null,/^image\/(jpeg|png|webp)$/.test(f.mimetype))});const q=(t,p=[])=>pool.query(t,p);const token=u=>jwt.sign({sub:u.id,org:u.organization_id,role:u.role},secret,{expiresIn:'7d'});function auth(req,res,next){try{req.user=jwt.verify((req.headers.authorization||'').replace('Bearer ',''),secret);next()}catch{return res.status(401).json({error:'No autorizado'})}}
app.get('/api/health',async(r,s)=>{await q('select 1');s.json({ok:true})});
app.post('/api/auth/register',async(req,res)=>{const{name,email,password,company,location,phone,description,depositPercent=50}=req.body;if(!name||!email||!password||!company)return res.status(400).json({error:'Faltan datos'});const c=await pool.connect();try{await c.query('BEGIN');const slug=company.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')+'-'+crypto.randomBytes(2).toString('hex');const org=(await c.query('insert into organizations(name,slug,description,location,phone,deposit_percent) values($1,$2,$3,$4,$5,$6) returning *',[company,slug,description,location,phone,depositPercent])).rows[0];const hash=await bcrypt.hash(password,12),u=(await c.query("insert into users(organization_id,email,name,password_hash,role) values($1,$2,$3,$4,'owner') returning id,organization_id,email,name,role",[org.id,email.toLowerCase(),name,hash])).rows[0];await c.query('COMMIT');res.status(201).json({token:token(u),user:u,organization:org})}catch(e){await c.query('ROLLBACK');res.status(400).json({error:e.code==='23505'?'El correo o empresa ya existe':'No se pudo crear la cuenta'})}finally{c.release()}});
app.post('/api/auth/login',async(req,res)=>{const u=(await q('select * from users where lower(email)=lower($1) limit 1',[req.body.email])).rows[0];if(!u||!await bcrypt.compare(req.body.password||'',u.password_hash))return res.status(401).json({error:'Credenciales incorrectas'});const org=(await q('select * from organizations where id=$1',[u.organization_id])).rows[0];res.json({token:token(u),user:{id:u.id,organization_id:u.organization_id,email:u.email,name:u.name,role:u.role},organization:org})});
app.get('/api/me',auth,async(req,res)=>{const org=(await q('select * from organizations where id=$1',[req.user.org])).rows[0];res.json({organization:org})});
app.get('/api/cabins',auth,async(req,res)=>res.json((await q('select c.*,coalesce(json_agg(p order by p.sort_order) filter(where p.id is not null),\'[]\') photos from cabins c left join cabin_photos p on p.cabin_id=c.id where c.organization_id=$1 group by c.id order by c.created_at desc',[req.user.org])).rows));
app.post('/api/cabins',auth,async(req,res)=>{const{name,type='Cabaña',description='',capacity=2,rate,bedrooms=1,beds=1,bathrooms=1}=req.body,slug=name.toLowerCase().replace(/[^a-z0-9áéíóúñ]+/gi,'-').replace(/(^-|-$)/g,'')+'-'+crypto.randomBytes(2).toString('hex');const row=(await q('insert into cabins(organization_id,name,slug,type,description,capacity,nightly_rate,bedrooms,beds,bathrooms) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning *',[req.user.org,name,slug,type,description,capacity,rate,bedrooms,beds,bathrooms])).rows[0];res.status(201).json(row)});
app.post('/api/cabins/:id/photos',auth,upload.array('photos',12),async(req,res)=>{const own=(await q('select id from cabins where id=$1 and organization_id=$2',[req.params.id,req.user.org])).rows[0];if(!own)return res.status(404).json({error:'Alojamiento no encontrado'});const out=[];for(let i=0;i<req.files.length;i++){const f=req.files[i],url=`http://localhost:${port}/uploads/${f.filename}`;out.push((await q('insert into cabin_photos(organization_id,cabin_id,storage_key,public_url,sort_order,is_cover) values($1,$2,$3,$4,$5,$6) returning *',[req.user.org,own.id,f.filename,url,i,i===0])).rows[0])}res.status(201).json(out)});
app.get('/api/public/organizations/:slug',async(req,res)=>{const org=(await q('select id,name,slug,description,location,phone,deposit_percent from organizations where slug=$1 and marketplace_enabled=true',[req.params.slug])).rows[0];if(!org)return res.status(404).json({error:'No encontrado'});const cabins=(await q("select c.*,coalesce(json_agg(p order by p.sort_order) filter(where p.id is not null),'[]') photos from cabins c left join cabin_photos p on p.cabin_id=c.id where c.organization_id=$1 and c.status='active' group by c.id",[org.id])).rows;res.json({organization:org,cabins})});
app.post('/api/public/reservations/quote',async(req,res)=>{const{cabinId,checkIn,checkOut,payOption='deposit'}=req.body,cabin=(await q('select c.*,o.deposit_percent from cabins c join organizations o on o.id=c.organization_id where c.id=$1',[cabinId])).rows[0];if(!cabin)return res.status(404).json({error:'No encontrado'});const nights=Math.ceil((new Date(checkOut)-new Date(checkIn))/86400000);if(nights<1)return res.status(400).json({error:'Fechas inválidas'});const conflict=(await q("select 1 from reservations where cabin_id=$1 and status not in ('cancelled','rejected') and $2<check_out and $3>check_in limit 1",[cabinId,checkIn,checkOut])).rowCount;if(conflict)return res.status(409).json({error:'Fechas no disponibles'});const total=cabin.nightly_rate*nights,percent=payOption==='full'?100:cabin.deposit_percent;res.json({nights,total,payOption,percent,payNow:Math.round(total*percent/100),balance:total-Math.round(total*percent/100)})});
app.listen(port,()=>console.log(`Hospeda API http://localhost:${port}`));
