CREATE TABLE organizations (id uuid PRIMARY KEY, name text NOT NULL, slug text UNIQUE NOT NULL, timezone text NOT NULL DEFAULT 'America/Santiago', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE users (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), email text NOT NULL, name text NOT NULL, role text NOT NULL CHECK(role IN ('owner','manager','reception','operations','accounting')), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(organization_id,email));
CREATE TABLE cabins (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), name text NOT NULL, capacity integer NOT NULL CHECK(capacity>0), nightly_rate integer NOT NULL CHECK(nightly_rate>=0), status text NOT NULL DEFAULT 'active', created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE guests (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), full_name text NOT NULL, phone text, email text, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE reservations (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), cabin_id uuid NOT NULL REFERENCES cabins(id), guest_id uuid NOT NULL REFERENCES guests(id), check_in date NOT NULL, check_out date NOT NULL, adults integer NOT NULL DEFAULT 1, children integer NOT NULL DEFAULT 0, channel text NOT NULL, status text NOT NULL, gross_amount integer NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), CHECK(check_out>check_in));
CREATE TABLE payments (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), reservation_id uuid NOT NULL REFERENCES reservations(id), amount integer NOT NULL, status text NOT NULL, method text NOT NULL, paid_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE operations_tasks (id uuid PRIMARY KEY, organization_id uuid NOT NULL REFERENCES organizations(id), cabin_id uuid NOT NULL REFERENCES cabins(id), reservation_id uuid REFERENCES reservations(id), type text NOT NULL CHECK(type IN ('cleaning','maintenance','inspection')), status text NOT NULL DEFAULT 'pending', assigned_to uuid REFERENCES users(id), due_at timestamptz NOT NULL, completed_at timestamptz);
CREATE INDEX reservations_calendar ON reservations(organization_id,cabin_id,check_in,check_out);
CREATE INDEX operation_queue ON operations_tasks(organization_id,status,due_at);
